import{i as d}from"./assets/vendor-I1I71QQ2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function u(n){const o=document.querySelector(".gallery");if(o.innerHTML="",n.length===0){d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const t=n.map(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:a,comments:c,downloads:l})=>`<a href="${e}" class="gallery-item">
            <img src="${s}" alt="${r}" loading="lazy" />
            <div class="info">
                <p>Likes: ${i}</p>
                <p>Views: ${a}</p>
                <p>Comments: ${c}</p>
                <p>Downloads: ${l}</p>
            </div>
        </a>`).join("");o.insertAdjacentHTML("beforeend",t)}function f(){document.querySelector(".loader").classList.remove("hidden")}function m(){document.querySelector(".loader").classList.add("hidden")}const h="47417637-c5af89f5f9dac842b4dab7627",p="https://pixabay.com/api/";function y(n){const o=`${p}?key=${h}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(t=>{if(!t.ok)throw new Error("Failed to fetch images");return t.json()}).then(t=>t.hits).catch(t=>{console.error(t)})}const g=document.querySelector(".search-form");g.addEventListener("submit",function(n){n.preventDefault();const o=n.target.elements.query.value.trim();if(!o){iziToast.warning({title:"Warning",message:"Please enter a search term."});return}f(),y(o).then(t=>{u(t)}).finally(()=>{m()})});
//# sourceMappingURL=index.js.map
